[package]
name = "polypolish"
version = "0.4.0"
authors = ["Ryan Wick <rrwick@gmail.com>"]
edition = "2018"
description = "a tool for polishing a long-read assembly with short reads"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
