[package]
name = "polypolish"
version = "0.4.0"
authors = ["Ryan Wick <rrwick@gmail.com>"]
edition = "2018"
description = "short-read polishing of long-read assemblies"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dependencies.clap]
version = "3.0.0-beta.2"
features = ["wrap_help"]
